--BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ; -- REPEATABLE READではWRITE SKEWを防げない。
UPDATE doctors SET on_call = false WHERE id = 1;
SELECT * from doctors;
